version: "3.9"
services:
  users-api:
    image: postgres:14.1
    container_name: users-api
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ${PWD}/docker/postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "8523:5432"
    expose:
      - 8523
